from __future__ import annotations

import json
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CURRENT = json.loads((ROOT / "public-membership.json").read_text(encoding="utf-8"))
SOURCE_RAW = (ROOT / "estate/canonical-hf-manifest.json").read_bytes()
SOURCE = json.loads(SOURCE_RAW)
PRIOR_RAW = (ROOT / "public-membership.observed-2026-09-10.json").read_bytes()
PRIOR = json.loads(PRIOR_RAW)
# The 2026-08-31 capture is preserved under a dated name; /public-inventory.json
# is now generated by scripts/generate_hf_inventory.py.
HISTORICAL = json.loads((ROOT / "public-inventory-2026-08-31.json").read_text(encoding="utf-8"))
GENERATED = json.loads((ROOT / "public-inventory.json").read_text(encoding="utf-8"))


def test_current_public_membership_is_exact_source_bound() -> None:
    assert CURRENT["schema"] == "szl.public-profile-inventory/v1"
    assert CURRENT["scope"]["id"] == "hf-public-author-membership/v1"
    assert CURRENT["scope"]["authentication"] == "none"
    assert CURRENT["scope"]["visibility"] == "public-only"
    assert CURRENT["counts"] == SOURCE["counts"]
    assert CURRENT["counts"] == {kind: len(SOURCE["inventory"][kind]) for kind in ("models", "datasets", "spaces")}
    assert CURRENT["observed_at"] == SOURCE["observedAt"]
    assert CURRENT["source_repository"] == "szl-holdings/a11oy"
    assert re.fullmatch(r"[0-9a-f]{40}", CURRENT["source_revision"])
    assert CURRENT["source_path"] == "docs/huggingface-ecosystem-manifest.json"
    assert CURRENT["source_sha256"] == hashlib.sha256(SOURCE_RAW).hexdigest()
    assert CURRENT["source_git_blob"] == hashlib.sha1(b"blob " + str(len(SOURCE_RAW)).encode() + b"\0" + SOURCE_RAW).hexdigest()
    assert CURRENT["scope_sha256"] == "9060fa8d7edcd5c246b86bcfcf1916df44b18038253325336f2f46208f8001ae"
    assert CURRENT["production_authorization"] is False
    assert CURRENT["runtime_readiness_inferred"] is False
    assert CURRENT["model_quality_inferred"] is False
    assert SOURCE["org"] == "SZLHOLDINGS"
    assert SOURCE["schemaVersion"] == 2
    assert SOURCE["inventoryScope"]["visibility"] == "public-only"
    assert SOURCE["inventoryScope"]["authenticated"] is False
    assert SOURCE["inventoryScope"]["privateAssetsIncluded"] is False
    for kind in ("models", "datasets", "spaces"):
        assert sorted(row["id"] for row in SOURCE["inventory"][kind]) == sorted(
            row["id"] for row in GENERATED["resources"][kind])
        assert all(row["private"] is False for row in SOURCE["inventory"][kind])


def test_prior_membership_bytes_and_evidence_remain_historical() -> None:
    assert hashlib.sha256(PRIOR_RAW).hexdigest() == "01059cc73de5aa6c10c8cede1059c8a27295606640bcb520e4684e46d4c2d22b"
    assert PRIOR["counts"] == {"datasets": 35, "models": 46, "spaces": 21}
    assert PRIOR["observed_at"] == "2026-09-10T03:20:41Z"
    assert PRIOR["source_revision"] == "4c6621b17ba452d5af7aa2460462fdfbe513509f"
    assert PRIOR["source_sha256"] == "04dc30206d499f004fe8151cfdf63700c380db29c2afc3d97d2a213303421ca2"
    assert PRIOR["evidence"]["workflow_run"] == 34432937958
    assert PRIOR["evidence"]["artifact"] == 10135145952


def test_detailed_august_snapshot_remains_historical_not_relabelled() -> None:
    assert HISTORICAL["schema"] == "szl.public-hf-inventory/v3"
    assert HISTORICAL["observed_at"] == "2026-08-31T18:59:11Z"
    assert HISTORICAL["observation_mode"] == "UNAUTHENTICATED_PUBLIC_API_SNAPSHOT"
    assert HISTORICAL["counts"]["models"] == 44
    assert HISTORICAL["counts"]["datasets"] == 30
    assert HISTORICAL["counts"]["spaces"] == 48
    assert HISTORICAL["observed_at"] != CURRENT["observed_at"]


def test_membership_scope_does_not_claim_collections_or_buckets() -> None:
    assert CURRENT["scope"]["collections_and_buckets"] == "outside-repository-membership-scope"
    assert "collections" not in CURRENT["counts"]
    assert "buckets" not in CURRENT["counts"]
    assert CURRENT["historical_portfolio_contract_replaced"] is False


def test_generated_inventory_is_current_and_not_the_historical_capture() -> None:
    assert GENERATED["schema"] == "szl.public-hf-inventory/v4"
    assert GENERATED["generated_by"] == "scripts/generate_hf_inventory.py"
    assert GENERATED["observation_mode"] == "UNAUTHENTICATED_PUBLIC_API_SNAPSHOT"
    assert GENERATED["private_assets"] == "NOT_OBSERVED"
    assert GENERATED["observed_at"] > HISTORICAL["observed_at"]
    assert {"path": "/public-inventory-2026-08-31.json", "observed_at": HISTORICAL["observed_at"],
            "schema": HISTORICAL["schema"]} in GENERATED["historical_snapshots"]


def test_kernel_membership_is_a_model_subset_and_auxiliary_resources_are_separate() -> None:
    resources = GENERATED["resources"]
    assert {row["id"] for row in resources["kernels"]} <= {row["id"] for row in resources["models"]}
    repository_total = sum(len(resources[kind]) for kind in ("models", "datasets", "spaces"))
    assert GENERATED["counts"]["repository_membership_total"] == repository_total
    assert GENERATED["counts"]["public_resources_total"] == repository_total + len(resources["collections"]) + len(resources["buckets"])
    assert GENERATED["claim_boundaries"]["kernel_membership"] == "MODEL_SUBSET_COUNTED_ONCE_IN_TOTALS"
    assert GENERATED["claim_boundaries"]["collections_and_buckets"] == "OUTSIDE_REPOSITORY_MEMBERSHIP_SCOPE"
